### ISSUE TITLE
Elasticsearch Junit K.O on some OS

### ISSUE THREAD

**Issue by mdhsl** [opensensorhub/osh-persistence#2]
It seems the junits don't pass because of this exception:
`java.lang.AssertionError: 0::/xdm
	at org.elasticsearch.monitor.os.OsProbe.getControlGroups(OsProbe.java:213)
	at org.elasticsearch.monitor.os.OsProbe.getCgroup(OsProbe.java:414)
	at org.elasticsearch.monitor.os.OsProbe.osStats(OsProbe.java:466)
	at org.elasticsearch.monitor.os.OsService.<init>(OsService.java:45)
	at org.elasticsearch.monitor.MonitorService.<init>(MonitorService.java:45)
	at org.elasticsearch.node.Node.<init>(Node.java:345)
	at org.elasticsearch.node.Node.<init>(Node.java:232)
	at org.elasticsearch.node.Node.<init>(Node.java:228)
	at org.sensorhub.impl.persistence.es.mock.TestEsBasicStorage.getNode(TestEsBasicStorage.java:90)
	at org.sensorhub.impl.persistence.es.mock.TestEsBasicStorage.<clinit>(TestEsBasicStorage.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:195)
	at org.junit.runners.BlockJUnit4ClassRunner$1.runReflectiveCall(BlockJUnit4ClassRunner.java:244)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:241)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:539)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:761)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:461)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:207)
`

**Comment by mdhsl** [comment]
Fixed in newer version of ES : [https://github.com/elastic/elasticsearch/issues/23218](https://github.com/elastic/elasticsearch/issues/23218)
